enum tokentypes {
    TCONST, TELSE, TIF, TINT, TRETURN, TVOID, TWHILE, TADD,TSUB,TMUL,TDIV,TMOD,TOP, TEQUAL, TNOTEQU, TLESSE,
	TGREATE,TNOT, TAND, TOR, TINC, TDEC, TADDASSIGN, TSUBASSIGN, TMULASSIGN, TDIVASSIGN, TMODASSIGN,
	TIDENT, TNUMBER,TBRASL,TBRASR,TBRAML,TBRAMR,TBRALL,TBRALR,TCOMMA,TSEMICOLON,TCMT,ILLSP,TOOLONG
};
